export const apiKey = 'ff9a6228ef16447db45110257252302';

export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'),
    'Partly Cloudy ': require('../assets/images/partlycloudy.png'),
    'Fog': require('../assets/images/fog.png'),
    'Mist': require('../assets/images/fog.png'),
    'Light snow': require('../assets/images/snow.png'),
    'Moderate snow': require('../assets/images/snow.png'),
    'Moderate or heavy snow showers': require('../assets/images/heavysnow.png'),
    'Patchy moderate snow': require('../assets/images/snow.png'),
    'Blowing snow': require('../assets/images/blowingsnow.png'),
    'Blizzard': require('../assets/images/blizzard.png'),
    'Moderate rain': require('../assets/images/lightrain.png'),
    'Patchy rain possible': require('../assets/images/lightrain.png'),
    'Patchy rain nearby': require('../assets/images/lightrain.png'),
    'Sunny': require('../assets/images/sun.png'),   
    'Clear': require('../assets/images/clear.png'),
    'Clear ': require('../assets/images/clear.png'),
    'Overcast ': require('../assets/images/cloudy.png'),
    'Cloudy ': require('../assets/images/cloudy.png'),
    'Light rain': require('../assets/images/lightrain.png'),
    'Light rain shower': require('../assets/images/lightrain.png'),
    'Light drizzle': require('../assets/images/lightrain.png'),
    'Light freezing rain': require('../assets/images/freezingrain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'),
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/thunder.png'),
    'other': require('../assets/images/partlycloudy.png'),
}

// images from: https://www.flaticon.com/packs/weather-flat-15610121