export const apiKey = 'ff9a6228ef16447db45110257252302';

export const weatherImages = {
    'sunny': require('../assets/images/weather7.png'),
    'clear': require('../assets/images/weather17.png'),
    'partly cloudy': require('../assets/images/weather.png'),
    'cloudy': require('../assets/images/weather3.png'),
    'overcast': require('../assets/images/weather16.png'),
    'mist': require('../assets/images/weather11.png'),
    'patchy rain possible': require('../assets/images/weather10.png'),
    'patchy rain nearby': require('../assets/images/weather10.png'),
    'patchy snow possible': require('../assets/images/weather13.png'),
    'patchy sleet possible': require('../assets/images/weather12.png'),
    'patchy freezing drizzle possible': require('../assets/images/weather6.png'),
    'thundery outbreaks possible': require('../assets/images/weather9.png'),
    'blowing snow': require('../assets/images/weather4.png'),
    'blizzard': require('../assets/images/weather2.png'),
    'fog': require('../assets/images/weather1.png'),
    'freezing fog': require('../assets/images/weather.png'),
    'patchy light drizzle': require('../assets/images/weather10.png'),
    'light drizzle': require('../assets/images/weather14.png'),
    'freezing drizzle': require('../assets/images/weather6.png'),
    'heavy freezing drizzle': require('../assets/images/weather15.png'),
    'patchy light rain': require('../assets/images/weather14.png'),
    'light rain': require('../assets/images/weather14.png'),
    'moderate rain at times': require('../assets/images/weather10.png'),
    'moderate rain': require('../assets/images/weather15.png'),
    'heavy rain at times': require('../assets/images/weather15.png'),
    'heavy rain': require('../assets/images/weather15.png'),
    'light freezing rain': require('../assets/images/weather6.png'),
    'moderate or heavy freezing rain': require('../assets/images/weather6.png'),
    'light sleet': require('../assets/images/weather14.png'),
    'moderate or heavy sleet': require('../assets/images/weather14.png'),
    'patchy light snow': require('../assets/images/weather13.png'),
    'light snow': require('../assets/images/weather13.png'),
    'patchy moderate snow': require('../assets/images/weather13.png'),
    'moderate snow': require('../assets/images/weather2.png'),
    'patchy heavy snow': require('../assets/images/weather2.png'),
    'heavy snow': require('../assets/images/weather2.png'),
    'ice pellets': require('../assets/images/weather2.png'),
    'light rain shower': require('../assets/images/weather15.png'),
    'moderate or heavy rain shower': require('../assets/images/weather15.png'),
    'torrential rain shower': require('../assets/images/weather15.png'),
    'light sleet showers': require('../assets/images/weather14.png'),
    'moderate or heavy sleet showers': require('../assets/images/weather14.png'),
    'light snow showers': require('../assets/images/weather13.png'),
    'moderate or heavy snow showers': require('../assets/images/weather2.png'),
    'light showers of ice pellets': require('../assets/images/weather13.png'),
    'moderate or heavy showers of ice pellets': require('../assets/images/weather13.png'),
    'patchy light rain with thunder': require('../assets/images/weather8.png'),
    'moderate or heavy rain with thunder': require('../assets/images/weather8.png'),
    'patchy light snow with thunder': require('../assets/images/weather9.png'),
    'moderate or heavy snow with thunder': require('../assets/images/weather9.png'),

    'other': require('../assets/images/weather.png'),
};


// images from: https://www.flaticon.com/packs/weather-flat-15610121